name: print-environment

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Select the environment"
        type: choice
        options:
          - dev1
          - dev2
          - qa
          - staging
          - production

jobs:
  print-env:
    name: Print Selected Environment
    runs-on: ubuntu-latest

    steps:
      - name: Set and Print Environment
        run: |
          ENV_NAME="${{ github.event.inputs.environment }}"
          echo "Selected Environment: $ENV_NAME"
