name: print-environment

on:
  push:
    branches:
      - '**'  # Trigger on all branches
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Select the environment"
        type: choice
        options:
          - dev1
          - dev2
          - qa
          - staging
          - production

jobs:
  print-env:
    name: Print Environment
    runs-on: ubuntu-latest

    steps:
      - name: Determine Environment
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ENV_NAME="${{ github.event.inputs.environment }}"
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            ENV_NAME="production"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            ENV_NAME="development"
          else
            ENV_NAME="${{ github.ref_name }}"
          fi

          echo "Selected Environment: $ENV_NAME"
