name: Crud-application-OIDC

on:
  push:
    paths:
      - 'complexityAI/**'
    branches:
      - DO-191
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment
        type: choice
        options:
          - dev
          - staging
          - Production

env:
  ECR_REPOSITORY: complexity-ai
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect changed directories
        id: set-matrix
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E '^(complexityAI)/' | cut -d/ -f1 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$CHANGED" >> $GITHUB_OUTPUT_
