jobs:
  build:
    name: Build and Deploy go-api
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'main' && 'production' || github.ref_name == 'develop' && 'development' || github.ref_name }}

    steps:
      - name: Set ENV_NAME variable
        run: echo "ENV_NAME=${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name == 'main' && 'production' || github.ref_name == 'develop' && 'development' || github.ref_name }}" >> $GITHUB_ENV

      - name: Print environment name
        run: echo "Environment: $ENV_NAME"
